spring.application.name=auth-service
server.port=8088

# Base de datos en Docker
spring.datasource.url=jdbc:mysql://localhost:3307/db_auth?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

# JPA VALIDATE 
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# JWT
jwt.secret=${JWT_SECRET:a98ba831524d428bdb59b2a9342de0716eaa901463593fb888e58001f522c74d}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Logs
logging.level.com.example.ms_auth=INFO

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.autoconfigure.exclude=org.springdoc.core.configuration.SpringDocHateoasConfiguration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html